# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestep',
            name='value',
            field=models.CharField(max_length=255, verbose_name='\u8f93\u5165\u503c'),
        ),
    ]
